another try

diff --git a/.github/workflows/ci-dockerhub.yml b/.github/workflows/ci-dockerhub.yml
--- a/.github/workflows/ci-dockerhub.yml
+++ b/.github/workflows/ci-dockerhub.yml
@@ -18,11 +18,18 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
 
+      - name: Check Docker secrets exist
+        run: |
+          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then echo "DOCKER_USERNAME missing/empty"; exit 1; fi
+          if [ -z "${{ secrets.DOCKER_PAT }}" ]; then echo "DOCKER_PAT missing/empty"; exit 1; fi
+          echo "Secrets are present"
+
+
       - name: Log in to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_TOKEN }}
+          password: ${{ secrets.DOCKER_PAT }}
 
 
       - name: Extract Docker metadata (tags, labels)
